spring.application.name=cloud

file.upload-dir=uploads

server.address=0.0.0.0
server.port=8080

spring.datasource.url=jdbc:h2:file:./data/cloudpage
spring.jpa.hibernate.ddl-auto=create

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

spring.datasource.username=sa
spring.datasource.password=

